// Material Design 3 inspired token sets. No hardcoded component colors elsewhere.
export const THEMES = {
  dark: {
    key: 'dark',
    name: 'Midnight',
    description: 'Balanced dark theme',
    background: '#101014',
    surface: '#17171d',
    surface1: '#1d1d25',
    surface2: '#24242e',
    surface3: '#2b2b37',
    outline: '#3a3a46',
    primary: '#b7a4ff',
    onPrimary: '#241a55',
    primaryContainer: '#3b2f7a',
    onPrimaryContainer: '#e6ddff',
    secondaryContainer: '#332f45',
    text: '#e7e4ee',
    textMuted: '#a49fb4',
    error: '#ffb4ab',
  },
  light: {
    key: 'light',
    name: 'Daylight',
    description: 'Clean light theme',
    background: '#fdfbff',
    surface: '#ffffff',
    surface1: '#f4f1fa',
    surface2: '#eeeaf6',
    surface3: '#e7e2f2',
    outline: '#cfc9db',
    primary: '#5b45b8',
    onPrimary: '#ffffff',
    primaryContainer: '#e6ddff',
    onPrimaryContainer: '#20005f',
    secondaryContainer: '#e6e0ef',
    text: '#1c1b20',
    textMuted: '#5e5a68',
    error: '#ba1a1a',
  },
  oled: {
    key: 'oled',
    name: 'Onyx',
    description: 'Pure black OLED',
    background: '#000000',
    surface: '#000000',
    surface1: '#0e0e12',
    surface2: '#16161c',
    surface3: '#1e1e26',
    outline: '#2a2a33',
    primary: '#b7a4ff',
    onPrimary: '#241a55',
    primaryContainer: '#332569',
    onPrimaryContainer: '#e6ddff',
    secondaryContainer: '#241f33',
    text: '#ededf2',
    textMuted: '#9c97a8',
    error: '#ffb4ab',
  },
  forest: {
    key: 'forest',
    name: 'Forest',
    description: 'Earthy green tones',
    background: '#0f1512',
    surface: '#131a16',
    surface1: '#18211c',
    surface2: '#1d2821',
    surface3: '#233028',
    outline: '#2f3d34',
    primary: '#8fd4a8',
    onPrimary: '#0d2f1c',
    primaryContainer: '#1d3f2c',
    onPrimaryContainer: '#c9f0d6',
    secondaryContainer: '#203026',
    text: '#e2ece5',
    textMuted: '#a0b0a5',
    error: '#ffb4ab',
  },
  blossom: {
    key: 'blossom',
    name: 'Blossom',
    description: 'Soft rose light',
    background: '#fff8f9',
    surface: '#ffffff',
    surface1: '#fdeef1',
    surface2: '#f8e3e8',
    surface3: '#f2d6dc',
    outline: '#d8c0c6',
    primary: '#b0485f',
    onPrimary: '#ffffff',
    primaryContainer: '#ffd9e0',
    onPrimaryContainer: '#400412',
    secondaryContainer: '#f1dce0',
    text: '#241a1c',
    textMuted: '#6e6063',
    error: '#ba1a1a',
  },
  honya: {
    key: 'honya',
    name: 'Honya Sakura',
    description: 'Pure black with sakura pink accents',
    background: '#000000',
    surface: '#000000',
    surface1: '#0a0a0f',
    surface2: '#111118',
    surface3: '#181822',
    outline: '#2a2a35',
    primary: '#ED8DB0',
    onPrimary: '#000000',
    primaryContainer: '#3d1f2e',
    onPrimaryContainer: '#FFF8F3',
    secondaryContainer: '#1a1218',
    text: '#FFF8F3',
    textMuted: '#a89ba0',
    error: '#ff6b6b',
  },
  ocean: {
    key: 'ocean',
    name: 'Ocean',
    description: 'Deep blue underwater tones',
    nameKey: 'theme.ocean.name',
    descriptionKey: 'theme.ocean.description',
    background: '#071A24',
    surface: '#0D2935',
    surface1: '#122F3D',
    surface2: '#163646',
    surface3: '#1B3D4F',
    outline: '#254A58',
    primary: '#28B8C7',
    onPrimary: '#04262B',
    primaryContainer: '#0F4A55',
    onPrimaryContainer: '#B8EDF2',
    secondaryContainer: '#167D91',
    text: '#E7F7FA',
    textMuted: '#91B8C0',
    error: '#ffb4ab',
  },
  amethyst: {
    key: 'amethyst',
    name: 'Amethyst',
    description: 'Rich purple jewel tones',
    nameKey: 'theme.amethyst.name',
    descriptionKey: 'theme.amethyst.description',
    background: '#120D1C',
    surface: '#1D1529',
    surface1: '#231A30',
    surface2: '#282038',
    surface3: '#2E253F',
    outline: '#4A3F5C',
    primary: '#9B6DFF',
    onPrimary: '#160B2E',
    primaryContainer: '#3B2770',
    onPrimaryContainer: '#E2D5FF',
    secondaryContainer: '#6D3BB5',
    text: '#F3EDFF',
    textMuted: '#B5A7C9',
    error: '#ffb4ab',
  },
  ember: {
    key: 'ember',
    name: 'Ember',
    description: 'Warm ember glow',
    nameKey: 'theme.ember.name',
    descriptionKey: 'theme.ember.description',
    background: '#1A0F0C',
    surface: '#291714',
    surface1: '#301C18',
    surface2: '#37211C',
    surface3: '#3E2721',
    outline: '#59433C',
    primary: '#E87845',
    onPrimary: '#2B0D03',
    primaryContainer: '#5A2A1C',
    onPrimaryContainer: '#FFE2CC',
    secondaryContainer: '#A8442A',
    text: '#FFF1E8',
    textMuted: '#C9A99B',
    error: '#ffb4ab',
  },
  arctic: {
    key: 'arctic',
    name: 'Arctic',
    description: 'Crisp cool light theme',
    nameKey: 'theme.arctic.name',
    descriptionKey: 'theme.arctic.description',
    background: '#F4F8FB',
    surface: '#FFFFFF',
    surface1: '#EDF3F8',
    surface2: '#E6EDF4',
    surface3: '#DFE8F0',
    outline: '#C4D0DA',
    primary: '#3B82B6',
    onPrimary: '#FFFFFF',
    primaryContainer: '#D3E7F7',
    onPrimaryContainer: '#0E3A5C',
    secondaryContainer: '#6BA8D1',
    text: '#17232D',
    textMuted: '#667784',
    error: '#ba1a1a',
  },
  coffee: {
    key: 'coffee',
    name: 'Coffee',
    description: 'Warm cozy brown tones',
    nameKey: 'theme.coffee.name',
    descriptionKey: 'theme.coffee.description',
    background: '#17120E',
    surface: '#241B15',
    surface1: '#2B2018',
    surface2: '#32251D',
    surface3: '#392B22',
    outline: '#4A3A2E',
    primary: '#D39A6A',
    onPrimary: '#2C1706',
    primaryContainer: '#59351C',
    onPrimaryContainer: '#F6D6B3',
    secondaryContainer: '#7A4E2C',
    text: '#F7EBDD',
    textMuted: '#B9A494',
    error: '#ffb4ab',
  },
  sage: {
    key: 'sage',
    name: 'Sage',
    description: 'Calm muted green tones',
    nameKey: 'theme.sage.name',
    descriptionKey: 'theme.sage.description',
    background: '#111713',
    surface: '#1B231D',
    surface1: '#212A23',
    surface2: '#273028',
    surface3: '#2D372E',
    outline: '#41503F',
    primary: '#9CAF88',
    onPrimary: '#1C2818',
    primaryContainer: '#3A4730',
    onPrimaryContainer: '#DCE8CE',
    secondaryContainer: '#4A5A3F',
    text: '#F0F4EA',
    textMuted: '#AAB5A2',
    error: '#ffb4ab',
  },
  rosewood: {
    key: 'rosewood',
    name: 'Rosewood',
    description: 'Deep burgundy tones',
    nameKey: 'theme.rosewood.name',
    descriptionKey: 'theme.rosewood.description',
    background: '#170D0E',
    surface: '#261416',
    surface1: '#2D191B',
    surface2: '#341F21',
    surface3: '#3B2426',
    outline: '#563B3E',
    primary: '#C66A72',
    onPrimary: '#2D0A0E',
    primaryContainer: '#5C2730',
    onPrimaryContainer: '#F6D2D2',
    secondaryContainer: '#823F49',
    text: '#F8E9E7',
    textMuted: '#B99A99',
    error: '#ffb4ab',
  },
  parchment: {
    key: 'parchment',
    name: 'Parchment',
    description: 'Warm vintage paper tones',
    nameKey: 'theme.parchment.name',
    descriptionKey: 'theme.parchment.description',
    background: '#F1E7D2',
    surface: '#FFF8E9',
    surface1: '#F7EEDD',
    surface2: '#F0E5D0',
    surface3: '#E9DCC4',
    outline: '#D5C3A6',
    primary: '#8A5A32',
    onPrimary: '#FFFFFF',
    primaryContainer: '#EBD8BE',
    onPrimaryContainer: '#3A2410',
    secondaryContainer: '#E8D3B4',
    text: '#30251D',
    textMuted: '#76695C',
    error: '#ba1a1a',
  },
  lemon: {
    key: 'lemon',
    name: 'Lemon',
    description: 'Warm golden yellow tones',
    nameKey: 'theme.lemon.name',
    descriptionKey: 'theme.lemon.description',
    background: '#17150A',
    surface: '#25220F',
    surface1: '#2C2915',
    surface2: '#34301B',
    surface3: '#3B3720',
    outline: '#554F2E',
    primary: '#E4C84A',
    onPrimary: '#2B2402',
    primaryContainer: '#5E541C',
    onPrimaryContainer: '#FAECB0',
    secondaryContainer: '#6E5D16',
    text: '#FFF9D8',
    textMuted: '#BDB58A',
    error: '#ffb4ab',
  },
};

export const isThemeDark = (t) => {
  const hex = String(t.background ?? '#000000').replace('#', '');
  const r = parseInt(hex.slice(0, 2) || '0', 16);
  const g = parseInt(hex.slice(2, 4) || '0', 16);
  const b = parseInt(hex.slice(4, 6) || '0', 16);
  return (0.299 * r + 0.587 * g + 0.114 * b) / 255 < 0.5;
};

export const RADIUS = { sm: 8, md: 12, lg: 16, xl: 24, pill: 999 };
export const READER_BACKGROUNDS = [
  { key: 'black', name: 'Pure black', bg: '#000000', fg: '#FFF8F3' },
  { key: 'dark', name: 'Dark', bg: '#15161a', fg: '#e2e2e6' },
  { key: 'mocha', name: 'Mocha', bg: '#2a211f', fg: '#e8d9c8' },
  { key: 'sepia', name: 'Sepia', bg: '#f4ecd8', fg: '#4a3c26' },
  { key: 'white', name: 'White', bg: '#ffffff', fg: '#16161a' },
];

export const SPACING = { xs: 4, sm: 8, md: 12, lg: 16, xl: 24, xxl: 32 };

export const TYPE = {
  display: { fontSize: 26, fontWeight: '800', letterSpacing: -0.4 },
  title: { fontSize: 20, fontWeight: '800', letterSpacing: -0.2 },
  section: { fontSize: 16, fontWeight: '800', letterSpacing: -0.1 },
  body: { fontSize: 14.5, fontWeight: '500' },
  bodyStrong: { fontSize: 14.5, fontWeight: '700' },
  label: { fontSize: 12.5, fontWeight: '600' },
  caption: { fontSize: 11.5, fontWeight: '600' },
};

/** Minimum comfortable Android touch target. */
export const TOUCH = 48;

/** Elevation that stays cheap on Android (no shadow rasterisation on low levels). */
export const ELEVATION = {
  none: {},
  low: { elevation: 2 },
  medium: { elevation: 4 },
  high: { elevation: 8 },
};

/** Adds an alpha channel to a #rrggbb token without allocating a color object. */
export const alpha = (hex, a = 1) => {
  const v = Math.round(Math.min(Math.max(a, 0), 1) * 255)
    .toString(16)
    .padStart(2, '0');
  return `${hex}${v}`;
};

/** Theme names are fixed English and bypass i18n, so `t` is intentionally unused. */
export const themeName = (t, theme) => theme.name;

export const themeDescription = (t, theme) =>
  theme.descriptionKey ? t(theme.descriptionKey) : theme.description;
